// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXTEK9vElvrLt9lN7f7OFGqdEX37WHvFs',
    appId: '1:90103062148:web:8a07e1d6099935eb212cd1',
    messagingSenderId: '90103062148',
    projectId: 'autohub-67126',
    authDomain: 'autohub-67126.firebaseapp.com',
    storageBucket: 'autohub-67126.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaxUaaSIgPd-wzOUJyMcGL8ivscRBmNak',
    appId: '1:90103062148:android:eb121132346e2b6c212cd1',
    messagingSenderId: '90103062148',
    projectId: 'autohub-67126',
    storageBucket: 'autohub-67126.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHjMeIWMth4UUXcjuIMHJ03l7Rk5SA-3A',
    appId: '1:90103062148:ios:4d3c02285ad20c8e212cd1',
    messagingSenderId: '90103062148',
    projectId: 'autohub-67126',
    storageBucket: 'autohub-67126.firebasestorage.app',
    iosBundleId: 'com.example.autohub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHjMeIWMth4UUXcjuIMHJ03l7Rk5SA-3A',
    appId: '1:90103062148:ios:4d3c02285ad20c8e212cd1',
    messagingSenderId: '90103062148',
    projectId: 'autohub-67126',
    storageBucket: 'autohub-67126.firebasestorage.app',
    iosBundleId: 'com.example.autohub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXTEK9vElvrLt9lN7f7OFGqdEX37WHvFs',
    appId: '1:90103062148:web:de6ebef3bef0696d212cd1',
    messagingSenderId: '90103062148',
    projectId: 'autohub-67126',
    authDomain: 'autohub-67126.firebaseapp.com',
    storageBucket: 'autohub-67126.firebasestorage.app',
  );
}
